### ISSUE TITLE
Fix the typos and styling

### ISSUE THREAD

**Issue by starlightknown** [starlightknown/AIry_pages#29]
**Describe the bug**
the styling of the paragraphs are not uniform and there are few typos in the about the game section of `mission.html` file

**Screenshots**
![image](https://user-images.githubusercontent.com/74637789/157023245-1fef8355-be05-4773-a43f-e65f31effa37.png)

**Comment by komalhadimani4444** [comment]
Please assign me this issue

**Comment by starlightknown** [comment]
Sure:)
