### ISSUE TITLE
Fix the typos

### ISSUE THREAD

**Issue by komalhadimani4444** [starlightknown/AIry_pages#37]
**Describe the bug**
There are few typos in the about the game section of README.md file

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/71191227/158177609-594dec99-2f1e-48d6-b146-fc260fd50cad.PNG)

**Comment by komalhadimani4444** [comment]
Assign me this issue maam

**Comment by starlightknown** [comment]
Done
